### ISSUE TITLE
empty transfers feild in fare_attributes is allowed 

### ISSUE THREAD

**Issue by pranavpandey1998official** [mapsme/just_gtfs#10]
empty transfers field in fare_attributes is allowed, and that means Unlimited transfers are permitted 

please check the specification (https://gtfs.org/reference/static#fare_attributestxt)

do you have some special technique to handle such conditions or you just treat this field as optional, https://github.com/mapsme/just_gtfs/blob/574b946dce6ee2392af91f632521633448878b75/include/just_gtfs/just_gtfs.h#L1843 here

**Comment by mesozoic-drones** [comment]
Good point! Yes, I handle this field incorrectly.
Bugfix: #11
