### ISSUE TITLE
Change default StopLocationType in Stop

### ISSUE THREAD

**Issue by BaqablH** [mapsme/just_gtfs#12]
`Stop` uses `StopLocationType::GenericNode` as default value. However, [the GTFS Reference](developers.google.com/transit/gtfs/reference/#stopstxt) states that its default value should be `StopLocationType::StopOrPlatform`

**Comment by mesozoic-drones** [comment]
Thank you! 
Merged fix to all relevant branches: master (with c++17 standard), for-usage-as-submodule (for simple including to projects) and cpp14 (with c++14 standard).
