### ISSUE TITLE
Campatiblity with c++ 14

### ISSUE THREAD

**Issue by pranavpandey1998official** [mapsme/just_gtfs#9]
Hi, I was working on a project which is not c++17 compatible, so I made a patch to made your library compatible with c++14 using boost, 
Can you look into it?
Can you accept it as a separate branch for other people to use

**Comment by mesozoic-drones** [comment]
Hello! I think it would be best to create it as separate branch (not master, something like cpp14). I leaved feedback to your pull-request with more details.

Thank you!

**Comment by mesozoic-drones** [comment]
Done.
